### ISSUE TITLE
Is there an option for inputting a password for the Redis DB?

### ISSUE THREAD

**Issue by dennisai** [ozkatz/announce.js#1]
If so, how do I configure it?  It doesn't look like it from the source.  This would be very helpful ASAP.

**Comment by ozkatz** [comment]
You are right, there is no support for password authentication against Redis at the moment.
I'll try and add it to the next release, probably soon.

**Comment by ozkatz** [comment]
since your pull request has already been merged and the proper documentation has been added - I'm closing this issue. feel free to reopen if anything comes up.
