### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by christianvuerings** [ozkatz/announce.js#3]
Would it be possible the add a license file to the repo?
We would like to try this out for our project but can't do that without a proper license.

**Comment by ozkatz** [comment]
Hi, you are 100% right for requesting this, you can expect it to happen very soon.
I'm pretty sure I will go with MIT, unless there is an overwhelming demand for something else..?

**Comment by christianvuerings** [comment]
MIT sounds fine, when would you be able to add this in?

**Comment by ozkatz** [comment]
the optimal answer would be "a few weeks ago" :)
but since this does keep a lot of people from using\contributing I will try and get it done as soon as today.

**Comment by ozkatz** [comment]
Added MIT license section to the README.

**Comment by christianvuerings** [comment]
@ozkatz Great, thanks
