### ISSUE TITLE
Please help//

### ISSUE THREAD

**Issue by anishmenon** [ozkatz/announce.js#6]
node server.js --config=/path/to/settings.json

is this necessary . and where is the  settings.json located ..
i'm implementing this on one of my Django App

**Comment by ozkatz** [comment]
If you plan to run with all the default settings you can run without it.

In case you do want to change some of the settings, simply create a file containing a JSON object. The possible attributes and values are listed [in the readme](https://github.com/ozkatz/announce.js#configuration).

a quick example of how that file should look would be:

```
{
    "storage": "redis",
    "redisHost": "some-redis-server",
    "redisPort": 6379
}
```

**Comment by eladmeidar** [comment]
@ozkatz Should probably add support for username, password and database specification.

**Comment by ozkatz** [comment]
@eladmeidar actually I'm working on a rewrite for Announce. The goal is to simplify the design and reduce the amount of state handled by the announce server. I also plan to introduce proper documentation and to improve the overall experience to make deployment and usage easier.

Adding database specification is definitely a good idea. I'll add it to the docs.
